// Builds one inline SVG sprite from the handful of lucide icons the app uses.
// No icon font, no runtime icon library: each <Icon> is a <use href="#i-name"/>.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "..", "node_modules", "lucide-static", "icons");
const ICONS = [
  "layout-dashboard", "building-2", "zap", "users", "activity", "layers", "flask-conical",
  "radio-tower", "play", "pause", "skip-back", "skip-forward", "gauge", "battery-charging",
  "sun", "moon", "cloud", "wind", "factory", "train-front", "droplets", "hospital", "school",
  "shield-check", "triangle-alert", "circle-check", "send", "x", "chevron-down", "chevron-left",
  "chevron-right", "search", "arrow-up-down", "arrow-up", "arrow-down", "sliders-horizontal", "cpu",
  "network", "timer", "signal", "refresh-cw", "info", "panel-left", "loader-circle", "check",
  "house", "lightbulb", "flame", "waves", "clock", "trending-down", "trending-up", "split",
  "server", "rows-3", "circle-dot", "gauge-circle", "plug-zap", "circle-pause",
];
const symbols = [];
for (const name of ICONS) {
  let svg;
  try { svg = readFileSync(join(src, `${name}.svg`), "utf8"); }
  catch { console.warn(`icon not found: ${name}`); continue; }
  const inner = svg.slice(svg.indexOf(">", svg.indexOf("<svg")) + 1, svg.lastIndexOf("</svg>"))
    .replace(/\s+/g, " ").trim();
  symbols.push(`<symbol id="i-${name}" viewBox="0 0 24 24">${inner}</symbol>`);
}
const out = `// generated by scripts/build-sprite.mjs (lucide icons, ISC licence). Do not edit.
export const SPRITE = ${JSON.stringify(symbols.join(""))};
export type IconName = ${ICONS.map((n) => JSON.stringify(n)).join(" | ")};
`;
writeFileSync(join(here, "..", "src", "icons", "sprite.gen.ts"), out);
console.log(`sprite: ${symbols.length} icons`);
